### ISSUE TITLE
Migration guide 2.12 to 2.13.x?

### ISSUE THREAD

**Issue by dorajistyle** [uikit/uikit#779]
Hello,
I use requirejs and uikit together.
The uikit 2.12.0  works fine. But after upgrade to 2.13.1 it's not works well.

When I use 'uikit.modal' function in javascript "undefined is not a function" error is occurred.
When I use 'data-uk-observe' attribute in html, "undefined is not a function" error is occurred.
