### ISSUE TITLE
TypeError in offsetViewport calculation fallback

### ISSUE THREAD

**Issue by martok** [uikit/uikit#5026]
### UIkit Version

3.18.1-3.21.5, but technically even before that

### Actual Behavior

On browsers without `window.visualViewport`, dropdowns don't work due to an issue with `offsetViewport`:
```
TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.
```
This can also be reproduced in browsers that would support it by commenting out the check in:
https://github.com/uikit/uikit/blob/4d6c5e2f9cdfb8158643074d297680f0a63e87e1/src/js/util/viewport.js#L168

### Expected Behavior

Dropdown should work, and it did up to (including) 3.18.0. Culprit commit was 4e943a6a0b50536bd9, but IMHO this is *not* a regression, just a coincidence.

### Additional Information

The issue is here:
https://github.com/uikit/uikit/blob/4d6c5e2f9cdfb8158643074d297680f0a63e87e1/src/js/util/viewport.js#L184-L189

The main issue is that `viewportElement` should be an Element, not a Document so that `css()` works. In this case, that would be `viewportElement.document.documentElement`.

But there is also something wrong with the logic.
What this does is try setting `rect[start]`, unless the `viewportElement` is a window, in which case the document is obtained and `rect[start]` remains uncalculated. Only the next iteration for the vertical case accesses the new element.
This looks like the referenced element should be checked before the loop and then used, so that all dimensions are calculated?

### Patch

I've tried the following locally and it does appear to work, let me know if you prefer a PR:

````diff
--- a/src/js/util/viewport.js
+++ b/src/js/util/viewport.js
@@ -177,16 +177,15 @@ export function offsetViewport(scrollElement) {
         return rect;
     }
 
+    if (isWindow(viewportElement)) {
+        viewportElement = viewportElement.document.documentElement;
+    }
+
     for (let [prop, dir, start, end] of [
         ['width', 'x', 'left', 'right'],
         ['height', 'y', 'top', 'bottom'],
     ]) {
-        if (isWindow(viewportElement)) {
-            // iOS 12 returns <body> as scrollingElement
-            viewportElement = viewportElement.document;
-        } else {
-            rect[start] += toFloat(css(viewportElement, `border-${start}-width`));
-        }
+        rect[start] += toFloat(css(viewportElement, `border-${start}-width`));
         const subpixel = rect[prop] % 1;
         rect[prop] = rect[dir] =
             viewportElement[`client${ucfirst(prop)}`] -
```

**Comment by janschoenherr** [comment]
Hi, what browser are you using?

**Comment by martok** [comment]
Hi!
This is in Pale Moon 33.2, but for testing purposes, the non-`visualViewport` branch fails in Chrome and Firefox with exactly the same error.

**Comment by martok** [comment]
Confirmed, works!

Thanks for not being one of those developers that would have just closed this as "works in my Chrome". Much appreciated! 👍
